### ISSUE TITLE
Adding Bill of materials

### ISSUE THREAD

**Issue by rsharanesh2002** [BalaDhinesh/elec-club_cord_self-project#1]
Based on the link which you sent just make  a table of the Bill of materials.
Link to what u sent:  https://hackaday.io/project/170429/components
Sample BOM : is attached
[elec-club-pro-bill.pdf](https://github.com/BalaDhinesh/elec-club_cord_self-project/files/4707646/elec-club-pro-bill.pdf)
[elect club-BOM.xlsx](https://github.com/BalaDhinesh/elec-club_cord_self-project/files/4707647/elect.club-BOM.xlsx)

**Comment by BalaDhinesh** [comment]
Added Bill Of Materials
Since the issue is solved, I am closing this issue.
